# Generated by Django 5.1.1 on 2025-05-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="John", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(default="Doe", max_length=30),
            preserve_default=False,
        ),
    ]
