from .document_actions import DocumentActionsAPIView
from .document_detail import DocumentDetailAPIView
from .document_version_detail import DocumentVersionDetailAPIView
from .document_version_list import DocumentVersionListAPIView
from .documents_list import DocumentListAPIView
