from .document_details import DocumentDetailAPIView
from .document_version_detail import DocumentVersionDetailAPIView
from .document_version_list import DocumentVersionListCreateAPIView
from .documents import DocumentListCreateAPIView
