# Generated by Django 5.1.7 on 2025-03-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_created=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.UUIDField(db_index=True, unique=True)),
                ("password_hash", models.CharField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
