# Generated by Django 5.1.7 on 2025-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
