# Generated by Django 5.1.1 on 2025-04-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_id_alter_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password_hash",
            new_name="password",
        ),
    ]
