# Generated by Django 5.1.1 on 2025-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_password_hash_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
