# Generated by Django 5.1.1 on 2025-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
