# Generated by Django 5.1.7 on 2025-03-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="document",
            table="documents",
        ),
        migrations.AlterModelTable(
            name="documentversion",
            table="documents_versions",
        ),
    ]
