# Generated by Django 5.1.7 on 2025-03-09 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_document_table_alter_documentversion_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="id",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
