# Generated by Django 5.1.1 on 2025-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_document_id_alter_document_document_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
