# Generated by Django 5.1.1 on 2025-04-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_document_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentversion",
            name="document",
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="DocumentVersion",
        ),
    ]
