# Generated by Django 5.1.1 on 2025-05-06 21:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="rewiewer",
            field=models.ForeignKey(
                default="30a30b48-e77c-4884-b579-9b582333ed0a",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rewiwer",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
