# Generated by Django 5.1.1 on 2025-05-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_document_type_alter_document_rewiewer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="rewiewer",
            new_name="reviewer",
        ),
    ]
